routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    abort,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)
from werkzeug.utils import secure_filename
from models.board import Board
from models.user import User
from models.topic import Topic
from models.reply import Reply
import os
import uuid

from routes import current_user
from utils import log

main = Blueprint('index', __name__)


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login u', u)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('login', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def user_detail():
    u = current_user()
    ts = topics(u.id)
    tn = topic_count(u.id)
    rs = replies(u.id)
    rn = reply_count(u.id)

    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u, topics=ts, topic_count=tn, Topic=Topic,  replies=rs, reply_count=rn)

def replies(id):
    ms = Reply.all(user_id=id)
    return ms

def reply_count(id):
    count = len(Reply.all(user_id=id))
    return count

def topics(id):
    ms = Topic.all(user_id=id)
    return ms

def topic_count(id):
    count = len(Topic.all(user_id=id))
    return count


def valid_suffix(suffix):
    valid_type = ['jpg', 'png', 'jpeg']
    return suffix in valid_type


@main.route('/image/add', methods=["POST"])
def add_img():
    # file 是一个上传的文件对象
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        # 上传的文件一定要用 secure_filename 函数过滤一下名字
        # ../../../../../../../root/.ssh/authorized_keys
        # filename = secure_filename(file.filename)
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        u = current_user()
        log('uuser',u)
        User.update(u.id, dict(
            user_image='/uploads/{}'.format(filename)
        ))

    return redirect(url_for(".profile"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory('user_image', filename)

@main.route("/setting")
def set_index():
    board_id = request.args.get('board_id', 'all')
    log('bbid:', board_id)
    u = current_user()

    # token = new_csrf_token()

    return render_template("setting.html", u=u, bid=board_id)

@main.route("/user_update", methods=["post"])
def user_update():
    form = request.form
    u = current_user()
    uid = u.id
    User.update(uid, form)
    return render_template("setting.html", u=u)

@main.route("/change_password", methods=["post"])
def change_password():
    form = request.form
    u = current_user()

    if u.password == User.salted_password(form['old_pass']):
        password = User.salted_password(form['new_pass'])
        u.new(dict(
            password=password,
        ))
        return render_template("setting.html", u=u)
    else:
        abort(501)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
from utils import log
from routes import *
import json

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = request.args.get('board_id', 'all')
    u = current_user()
    if board_id == 'all':
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    # log('mmmsss:', type(ms), ms[-1])
    # if r.exists(board_id):
    #     log('hit redis')
    #     json_string = r.get(board_id)
    #     json_list = json.loads(json_string)
    # else:
    #     print('not hit redis')
    #     json_list = []
    #     for m in ms:
    #         j = m.json()
    #         j['replies'] = m.replies()
    #         j['user_image'] = m.user().user_image
    #         json_list.append(j)
    #     json_string = json.dumps(json_list)
    #     r.set(board_id, json_string)
    # ms = json_list

    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, u=u)


@main.route('/<string:id>')
def detail(id):
    t = Topic.find(id=id)
    author = t.user()
    b = t.board()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=t,  b=b, au=author)


@main.route("/add", methods=["POST"])
# @login_required
@csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route("/delete")
@csrf_required
def delete():
    id = request.args.get('id')
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = request.args.get('board_id')
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/'>首页</a></li>

        <li>
            <a href='/my/messages'>

              未读消息
            </a>
        </li>

        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}

<div id="footer">
  <div id="footer_main">
    <div class="links">
      <a class="dark" href="https://cnodejs.org/rss">RSS</a>
      |
      <a class="dark" href="https://github.com/cnodejs/nodeclub/">源码地址</a>
    </div>

    <div class="col_fade">

  <p>CNode 社区为国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究。</p>
  <p>服务器赞助商为
    <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo" target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
      <img src="https://dn-cnode.qbox.me/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
    </a>
  ，存储赞助商为
    <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="qiniu_bottom">
      <img src="https://dn-cnode.qbox.me/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
    </a>
  ，由<a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="alinode_bottom">
      <img src="https://dn-cnode.qbox.me/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode" height="54px" width="166px">
    </a>提供应用性能服务。
  </p>


    </div>
</div></div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
{% extends "base.html" %}
{% block title %}
论坛主页
{% endblock %}
{% block main %}

<div id="main">
    <div id="content">

        <div class="panel">
        <div class="header">
          <ul class="breadcrumb">
            <li>
                <a href="http://127.0.0.0:3000/">主页</a>
                <span class="divider">/</span></li>
          </ul>
        </div>

        <div class="inner userinfo">
            {% set u = user %}
          <div class="user_big_avatar">
            <img src="{{u.user_image}}" class="user_avatar" title="{{u.username}}">
          </div>
          <a class="dark">{{u.username}}</a>

          <p class="col_fade">注册时间 1 年前</p>

        </div>
      </div>


        <div class='panel'>
        <div class='header'>
            <span class="col_fade">最近创建的话题</span>
        </div>
        <div class="inner padding">
        {% if (topic_count > 0 ) %}
        {% for t in topics %}

            {% set u = t.user() %}
            <div class='cell topic_area topic_item'>
                <a class='author_content'>
                    <a class="user_img">
                        <img src="{{u.user_image}}"
                             title="{{ u.username }}"/>
                        <a class="topic_view">
                            {{ t.reply_count() }} / {{ t.views }}
                        </a>
                    </a>
                    <a class="topic_title_wrapper">
                         <a class="topic_title" style="color:blue;" href="{{ url_for('topic.detail', id=t.id) }}"  >
                                    {{ t.title }}
                         </a>
                    </a>
                    <span class='reply_info' style="float:right">
                    {% if (t.reply_count()>0) %}
                    {% set last_r = t.last() %}

                        <img src="{{last_r.user().user_image}}" width=30px style="float:top" title="{{ last_r.user().username }}">
                        <span class="liu-time" data-ct="{{ t.ct }}"></span>



                    {% endif %}
                    </span>
                </a>
            </div>
        {% endfor %}
        {% else %}
        <div class="inner">
          <p>无话题</p>
        </div>
        {% endif %}


    </div>
        </div>

        <div class='panel'>
        <div class='header'>
            <span class="col_fade">最近参与的话题</span>
        </div>
        <div class="inner padding">
        {% if (reply_count > 0 ) %}
        {% for r in replies %}

            {% set ts = Topic.all(id=r.topic_id) %}
            {% for t in ts %}
            <div class='cell reply_area reply_item'>
                <a class='author_content'>
                    <a class="user_img">
                        <img src="{{t.user().user_image}}"
                             title="{{ t.user().username }}"/>
                        <a class="reply_view">
                            {{ t.reply_count() }} / {{ t.views }}
                        </a>
                    </a>
                    <a class="reply_title_wrapper">
                         <a class="topic_title" style="color:blue;" href="{{ url_for('topic.detail', id=t.id) }}"  >
                                    {{ t.title }}
                         </a>
                    </a>
                    <span class='reply_info' style="float:right">
                    {% if (t.reply_count()>0) %}
                    {% set last_r = t.last() %}

                        <img src="{{last_r.user().user_image}}" width=30px style="float:top" title="{{ last_r.user().username }}">
                        <span class="liu-time" data-ct="{{ t.ct }}"></span>

                    {% endif %}
                    </span>
                </a>
            </div>
            {% endfor %}
        {% endfor %}
        {% else %}
        <div class="inner">
          <p>无话题</p>
        </div>
        {% endif %}


    </div>
        </div>

    </div>
</div>

    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            var code_list = es('pre code')
            for (var i = 0; i < code_list.length; i++) {
                var code = code_list[i]
                code.className = code.className.replace('lang', 'language')
            }
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.liu-time')
                for (var i = 0; i < times.length; i++) {
                    var t = times[i]
                    var time = Number(t.dataset.ct)
                    var now = Math.floor(new Date() / 1000)
                    var delta = Math.floor((now - time) / 3600)
                    var day = Math.floor(delta / 24)
                    var delta = delta % 24
                    var s = `${day}天,${delta} 小时前`
                    t.innerText = s
                }
            }, 1000)
        }

        var __main = function () {
            markContents()
            registerTimer()
            highlight()
        }

        __main()
    </script>

{% endblock %}

templates/setting.html
{% extends "base.html" %}
{% block title %}
论坛主页
{% endblock %}
{% block main %}
<div id="main">

    <div id='sidebar'>
            <div class='panel'>
            <div class='header'>
              <span class='col_fade'>个人信息</span>
            </div>
            <div class='inner'>
            <div class='user_card'>

                <a class='user_avatar' href="{{ url_for('index.user_detail', id=u.id) }}">
                    <img src="{{u.user_image}}" title="u.username"/>
                </a>
                <span class='user_name'><a class='dark' href="{{ url_for('index.user_detail', id=u.id) }}">
                            {{ u.username }}
                </a></span>
                <div class="space clearfix"></div>
                 <span class="signature">
                “

                    这家伙很懒，什么个性签名都没有留下。

                ”
            </span>
            </div>
            </div>
            </div>
            <div class="panel">
                <div class="inner">
                    <a href="/topic/new" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
   </div>

    <div id="content">

        <div class="panel">
        <div class="header">
          <ul class="breadcrumb">
            <li>
                <a href="http://127.0.0.0:3000/">主页</a>
                <span class="divider">/ 设置</span></li>
          </ul>
        </div>
        </div>
        <div class="panel">
        <div class="inner">

          <form id="setting_form" class="form-horizontal" action="{{ url_for('.user_update') }}" method="post">
            <div class="control-group">
              <label class="control-label" for="username">用户名</label>

              <div class="controls">
                <input class="input-xlarge " id="username" name="username" size="30" type="text" value="{{u.username}}">
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="signature">个性签名</label>

              <div class="controls">
                <textarea class="input-xlarge" id="signature" name="signature" size="30">{{u.signature}}</textarea>
              </div>
            </div>

            <div class="form-actions">
              <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
            </div>
          </form>
        </div>
      </div>

        <div class="panel">
        <div class="header">
          <span class="col_fade">更改密码</span>
        </div>
        <div class="inner">
          <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.change_password') }}" method="post">
            <div class="control-group">
              <label class="control-label" for="old_pass">当前密码</label>

              <div class="controls">
                <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="new_pass">新密码</label>

              <div class="controls">
                <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
              </div>
            </div>
            <input type="hidden" id="action" name="action" value="change_password">


            <div class="form-actions">
              <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
            </div>
          </form>
        </div>
      </div>

        <div class="panel">
        <div class="header">
          <span class="col_fade">上传头像</span>
        </div>
        <div class="inner">
        <form method=post
              action='{{ url_for(".add_img") }}'
              enctype=multipart/form-data>
            <input type=file name=avatar>
            <!--<input type=submit value=Upload>-->
            <button type="submit">Upload</button>
        </form>
        </div></div>
    </div>

{% endblock %}